name: Build And Test
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/**"
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  coverage:
    name: Sonar Coverage Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm ci
      - name: Test and coverage
        run: npm run test:ci
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
